[firebase]
type = "service_account"
project_id = "hello-world-e1f7d"
private_key_id = "5a172f9775971d25a9b4752c05265c5b5cd46429"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCiJtsEMBmDatXO
2WKUlmj1YG1HHizjA6xaOEgcvvJqsR33QPXK8nshokWmZHM2T3VSzxPTcfPVTymu
a1U3rUTTAcdeABSs4qPeneqishOX324HsjTZRXglsaHjHnzuYeWIWWjmZqolIqMe
eR5001YyyZZRaUMWJB0rICEkGGaXxBPUpRSW/rwVGLvvbGg9yKMdEi5s7wW/D+5s
yrpN0i6UX/OtlGuN2rtovSRYems4cM4t1qmQcWpponclWmR+GwkMBzKSSk+xchaw
PdYyMJH7jyBJWRhWxH403c24IS9USbsChKEeJyaNXxPMlfTMbWF1eP9/QYw0AD0F
0dz/TMzrAgMBAAECggEAARlNXi8xBntQn9eE0I+MYC8xzmJlJC6Sx17qCIqo1l0y
UQZGYF7DHiT/BIp4E4XKUwpk6Q80vzdPLVqWf3xT0CFO1o+mDLCzjTt5qv2F8Wi1
JVpSvz4uzeZaYW+EC1Y3NBpmER1n0JdurLqLRmkLhJzTObdr1kHAKNoRW6lhBcdu
j69CxwElbc7V6SIONGdS9iEhs566L4jWPY8q1EujsxZjdmB/ZUHeMvUmGYH05Xl9
w+Hlc88KhPRqJHav2xZnvales5Gt/hJ6UYlfe1yNv994MhNk77YzFtl5G/wM5Gdk
EflG7Jb2dOnJ7aAyYN9W7DGNZWr32HJO6qIOkmWQ4QKBgQDSbcdxnmIuQCrBJ5bz
PlKiVhrWbEqYnOKxnoFCWYyNFJPn6fOpOQZtMipFYeV8WzGW3desQEq2JPaD3xop
pFoI/2OyO1HEHDsVBCgq74VWxklvlmvU80dJdlvjt/4EgvJd1/6mmXKrwFyovSG1
cgkLyWRgPepGuveOpzLNZQRXUwKBgQDFRJYY4iQjBC30j0vEr8d5qqJEGz/mxw4J
cf5gmLkwk2mZ7924TOmkM2xaagmczCM9cBBk99fq/zvUqJQixVOuKJ27NDvMfSQQ
g+muOk6iYR+ssFCjdGX1aTYwXZh0rV86eOLo0+joUzVniEufx4hTorg5UC+MvoXl
GIzeyTL5CQKBgF+tNm+8mdt5pXbpb0Lt5ViWWeGAn3JAcvpbnV3zpWpIHu/lebpJ
iViA5KNjXZprRGLaP0O8f7vNlqBjAlxIs/8/T68sNYM7asmleDX9bd0Ej0NDW4gZ
jSIjxKgHcmHOwDBXExvgzTi2X+sBA6CiVuabDR6NSEYcoI6mCv1EnvKtAoGAZwe0
cVijURqcue+hvh+kypnhWDr3PBxY63v7RQ5fIszLSdgq8FhTayxkejCJxrgj67G9
Dk8YGaem4yINBMAVPY//GchlNx9hF7Md+J6BdXPOrE4GP+jKW8vQvqATwVTPuOVs
dfg/3B+hc+qOvOvk+vGw0FZeD19u5UHWSYHCOqkCgYEAi7Inds0/rzdJwcTbYNqr
m5qreLmICHd35QaH/KWlAg53UAtGQOnGuAIriAZAFIteMQq9HaZjZ8ehcfjDvLyc
nckoq0OrxklnlNaiMgTeXZ+JWzgtRRVCVudYcyjwhQIastPfTKAqrFqNV3ePRXhI
w/3wpi1Tj4dm/bh+IG7AmUY=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-9hkev@hello-world-e1f7d.iam.gserviceaccount.com"
client_id = "106102732246229067688"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-9hkev@hello-world-e1f7d.iam.gserviceaccount.com"
